### PR TITLE
Convert to TypeScript

### LINKED ISSUE #35: throw error when model name does not exist
Hello!

Orgs in an export name, and Organization is the name of the mongoose model.

```
import mockingoose from 'mockingoose'
import Orgs from '../org'

it('should return no orgs if none exist', () => {
  mockingoose.Orgs.toReturn([])

  return Orgs.find().then(result => {
    expect(result).toHaveLength(0)
  })
})
```

throws this error:
```
 FAIL  src/models/__test__/org.test.js
  ● should return no orgs if none exist

    expect(received)[.not].toHaveLength(length)

    Expected value to have a 'length' property that is a number. Received:
      undefined

       6 | 
       7 |   return Orgs.find().then(result => {
    >  8 |     expect(result).toHaveLength(0)
         |                    ^
       9 |   })
      10 | })
      11 | 

      at src/models/__test__/org.test.js:8:20
```

This is the correct test:
```
import mockingoose from 'mockingoose'
import Orgs from '../org'

it('should return no orgs if none exist', () => {
  mockingoose.Organization.toReturn([])

  return Orgs.find().then(result => {
    expect(result).toHaveLength(0)
  })
})
```

Can we get a better error message?

Thanks!

### PR DESCRIPTION
**Pull request by andreialecu**
Not sure if you would be interested in this, but there are various benefits for libraries to be written in TypeScript, including better editor support.

Writing it in TypeScript ensures the exported API is always in sync with the type definitions, so it is preferable to writing external types.

It's still usable in plain JS, and all tests pass.

I have also added an alternative and preferred way to set up mocks for models, changing from `mockingoose.Model` to `mockingoose(Model or 'Model')`. Old method is still supported.

This is nice because `Model` can be a direct reference to a model class, so strong typing and compile type checks are available. This brings the benefit of editor IDE refactoring of model names as well. Developers could update the name of a model and IDEs, like VSCode, would know to rename the mockingoose reference to the model as well.

Closes #35

### CODE REVIEW

**Comment by jozsi** [comment]
Hey @andreialecu! Thanks a lot for your contribution, I'm looking forward to see this merged. However, I tried both #51 and #51 by including it as `    "mockingoose": "andreialecu/mockingoose#typescript",`, but I'm getting this:
`ObjectParameterError: Parameter "obj" to Document() must be an object, got function mockConstructor()`
for the below code:
```
  const returnMock = jest.fn();
  mockingoose.User.toReturn(returnMock, 'findOne');
```

I wonder, is the build correct or am I missing something?

**Comment by alonronin** [comment]
Very nice, maybo `mockingoose` can be a function itself so you can:

```
mockingoose(Model, 'Model').toReturn(...)
```

also we can get the modelName from Model so we can pass only Model.

**Comment by andreialecu** [comment]
@alonronin I'm not sure it would be possible to keep your current `Proxy` type implementation for backwards compatibility and also make `mockingoose` a function.

@jozsi You probably need to provide a return value like:

```
const returnMock = jest.fn().mockReturnValue({ name: 'test' });
mockingoose.User.toReturn(returnMock, 'findOne');
```

**Comment by jozsi** [comment]
@andreialecu - I tried with a return value first, then simplified it to a plain mock fn. Tried again to make sure, but no luck. I can create a repo to reproduce, if you wish.

@alonronin - glad to see this merged! Is there any ETA for a release?

**Comment by andreialecu** [comment]
@jozsi sure, I could take a look at a repo. I tried the test above and it worked. I'm also using it exactly like `"mockingoose": "andreialecu/mockingoose#typescript"` in my own project and it also seems to work properly.

**Comment by andreialecu** [comment]
@jozsi also try updating from my github, there have been some more commits, maybe you're on an older one that had a problem.

**Comment by jozsi** [comment]
No luck. Here is the link reproducing the error: https://github.com/jozsi/mockgoose-bug

**Comment by andreialecu** [comment]
Hey @jozsi, found the problem and fixed it. It seems that `jest.fn()` isn't `instanceof Function` so I changed the check.

It would've worked if called like `mockingoose.User.toReturn(() => { name: 'test' }, 'findOne');`

But should work with your usage now too.

**Comment by jozsi** [comment]
Works great now, thanks! Would worth mentioning in the docs the usage of `query.getQuery()`, for those who want to compare the received parameters. Cause blindly, my first attempt was:
```
    expect(returnMock).toHaveBeenCalledWith({
      email: user.email.toLowerCase(),
    });
```
that does not work and I completely understand the (reason)[https://github.com/alonronin/mockingoose/issues/47]

**Comment by andreialecu** [comment]
It is mentioned in the docs, since #50. See https://github.com/alonronin/mockingoose#mockingoosemodelnametoreturnfn-operation--find

**Comment by andreialecu** [comment]
FWIW, in my tests I use this one liner:

```
      mockModel(User).toReturn((q: Query<User>) => (expect(q.getQuery()).toMatchSnapshot('query'), user), 'findOne');
```

It's readable for me, using the [comma operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator)

**Comment by alonronin** [comment]
> @alonronin I'm not sure it would be possible to keep your current `Proxy` type implementation for backwards compatibility and also make `mockingoose` a function.
> 
> @jozsi You probably need to provide a return value like:
> 
> ```
> const returnMock = jest.fn().mockReturnValue({ name: 'test' });
> mockingoose.User.toReturn(returnMock, 'findOne');
> ```

You can trap function call:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/apply

**Comment by alonronin** [comment]
I want to proceed with this PR and merge it for the next release.

@andreialecu can you introduce prettier to the project using its default settings? so the code will look consist.

@andreialecu would you like to join as a co-contributer (you will be able to merge pr's and make releases)

**Comment by andreialecu** [comment]
@alonronin I added `prettier` and `tslint` and reformatted all code.

Also added the ability to call `mockingoose(model)` and removed `mockModel()` from exports, and updated the README with this new recommended usage.

Regarding joining as a contributor, sure, add me! :)

**Pull request merged**
